project:
  type: website

website:
  title: "chumin-data-preprocessing"
  navbar:
    search: true
    background: dark
    logo: ./img/logo.png
    left:
      - href: index.qmd
        text: "Home"
        icon: house-door-fill
      - href: ./about/about.qmd
        text: "about"
        icon: egg-fried
      - href: ./assignment/contact.qmd
        text: "assignment"
        icon: clipboard-data
  sidebar: 
    - id: about
      title: "about"
      style: floating
      collapse-level: 1
      align: left
      contents: 
        - ./about/about.qmd
        - text: "frontdoor"
          href: ./about/front-door.qmd  
    - id: assignment
      title: "assignment"
      style: floating
      collapse-level: 1
      align: left
      contents: 
        - ./assignment/contact.qmd
        - text: "개인과제04"
          href: ./assignment/개인과제04.qmd
        - text: "개인과제05"
          href: ./assignment/개인과제05.qmd
        - text: "개인과제06"
          href: ./assignment/개인과제06.qmd
          
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    highlight-style: monokai

editor: visual

